apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ve3eu4t8o-nodejs 
  janus-idp.io/tekton: ve3eu4t8o-nodejs
  backstage.io/kubernetes-id: ve3eu4t8o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ve3eu4t8o-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml