apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ve3eu4t8o-nodejs
  janus-idp.io/tekton: ve3eu4t8o-nodejs
  backstage.io/kubernetes-id: ve3eu4t8o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ve3eu4t8o-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
